package com.chuanphat.warranty.inventory;

import static org.assertj.core.api.Assertions.assertThat;

import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

class WarehouseAccessBackfillMigrationTest {
    @Test
    void backfillMigrationPreservesExistingAccessAtDeployTime() {
        DataSource dataSource = dataSource();
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("create table app_users (id bigint primary key, branch_id bigint)");
        jdbc.execute("create table employees (id bigint primary key, user_id bigint, branch_id bigint)");
        jdbc.execute("create table user_branch_access (id bigint generated by default as identity primary key, user_id bigint, branch_id bigint)");
        jdbc.execute("create table warehouses (id bigint primary key, branch_id bigint)");
        jdbc.update("insert into app_users(id, branch_id) values (10, 1), (20, 2)");
        jdbc.update("insert into employees(id, user_id, branch_id) values (100, 10, 1), (200, 20, 2)");
        jdbc.update("insert into user_branch_access(user_id, branch_id) values (10, 1)");
        jdbc.update("insert into warehouses(id, branch_id) values (1000, 1), (1001, 1), (2000, 2)");

        new ResourceDatabasePopulator(new ClassPathResource("db/migration/V64__employee_warehouse_access.sql"))
                .execute(dataSource);

        assertThat(jdbc.queryForObject(
                "select count(*) from employee_warehouses where employee_id = 100 and access_level = 'OPERATE'",
                Integer.class)).isEqualTo(2);
        assertThat(jdbc.queryForObject(
                "select count(*) from employee_warehouses where employee_id = 200 and warehouse_id = 2000 and access_level = 'OPERATE'",
                Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("select count(*) from employee_warehouses", Integer.class)).isEqualTo(3);
    }

    private DataSource dataSource() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:warehouse-backfill;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        return dataSource;
    }
}
