-- ERP-style authorization schema reference.
-- Development/test still use Hibernate ddl-auto=update; run this for production databases.

ALTER TABLE permissions ADD COLUMN IF NOT EXISTS module VARCHAR(50);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS action VARCHAR(50);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS description VARCHAR(500);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS system_role BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL;

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS user_branch_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    access_level VARCHAR(20) NOT NULL,
    CONSTRAINT uq_user_branch_access UNIQUE (user_id, branch_id),
    CONSTRAINT ck_user_branch_access_level CHECK (access_level IN ('VIEW', 'OPERATE', 'MANAGE'))
);

INSERT INTO user_roles (user_id, role_id)
SELECT id, role_id FROM app_users
WHERE role_id IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO user_branch_access (user_id, branch_id, access_level)
SELECT id, branch_id, 'MANAGE' FROM app_users
WHERE branch_id IS NOT NULL
ON CONFLICT DO NOTHING;

UPDATE permissions
SET module = split_part(code, '_', 1),
    action = substring(code from length(split_part(code, '_', 1)) + 2)
WHERE module IS NULL OR action IS NULL;

INSERT INTO permissions (code, module, action) VALUES
('PRODUCT_VIEW', 'PRODUCT', 'VIEW'),
('PRODUCT_CREATE', 'PRODUCT', 'CREATE'),
('PRODUCT_UPDATE', 'PRODUCT', 'UPDATE'),
('PRODUCT_DELETE', 'PRODUCT', 'DELETE'),
('PRODUCT_EXPORT', 'PRODUCT', 'EXPORT'),
('SALES_VIEW', 'SALES', 'VIEW'),
('SALES_CREATE', 'SALES', 'CREATE'),
('SALES_CANCEL', 'SALES', 'CANCEL'),
('SALES_DISCOUNT_APPROVE', 'SALES', 'DISCOUNT_APPROVE'),
('INVENTORY_TRANSFER_APPROVE', 'INVENTORY', 'TRANSFER_APPROVE'),
('ACCOUNTING_POST', 'ACCOUNTING', 'POST'),
('REPORT_EXPORT', 'REPORT', 'EXPORT'),
('SETTING_MANAGE', 'SETTING', 'MANAGE')
ON CONFLICT (code) DO NOTHING;
