-- Sales/POS professional schema reference.
-- The app currently relies on Hibernate ddl-auto=update in dev; this file documents
-- the intended database surface for future Flyway/Liquibase adoption.

ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS quotation_id BIGINT;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS voucher_code VARCHAR(50);
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS note VARCHAR(500);
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS reservation_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS returned_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS accounting_recorded BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS stock_issued BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS warranty_created BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS voucher_consumed BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE sales_order_items ADD COLUMN IF NOT EXISTS warehouse_id BIGINT;
ALTER TABLE sales_order_items ADD COLUMN IF NOT EXISTS returned_quantity INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE product_serials ADD COLUMN IF NOT EXISTS warehouse_id BIGINT;
ALTER TABLE product_serials ADD COLUMN IF NOT EXISTS reserved_order_no VARCHAR(80);
ALTER TABLE product_serials ADD COLUMN IF NOT EXISTS reservation_until TIMESTAMP WITH TIME ZONE;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS template_code VARCHAR(80);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS template_snapshot VARCHAR(2000);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS electronic_invoice_provider VARCHAR(80);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS electronic_invoice_status VARCHAR(40);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS electronic_invoice_ref VARCHAR(120);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS applicable_product_ids VARCHAR(500);
ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS applicable_branch_ids VARCHAR(500);

ALTER TABLE warranties ADD COLUMN IF NOT EXISTS customer_id BIGINT;
ALTER TABLE warranties ADD COLUMN IF NOT EXISTS invoice_no VARCHAR(80);

CREATE TABLE IF NOT EXISTS quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_no VARCHAR(50) NOT NULL UNIQUE,
    branch_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    quotation_date DATE NOT NULL,
    valid_until DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    subtotal NUMERIC(14, 2) NOT NULL,
    discount_amount NUMERIC(14, 2) NOT NULL,
    total_amount NUMERIC(14, 2) NOT NULL,
    voucher_code VARCHAR(50),
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id BIGINT NOT NULL REFERENCES quotations(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    serial_id BIGINT REFERENCES product_serials(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    line_total NUMERIC(14, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_orders(id),
    payment_method VARCHAR(30) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    payment_date DATE NOT NULL,
    bank_account_id BIGINT,
    reference_no VARCHAR(80),
    note VARCHAR(500),
    installment_disbursement BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS installment_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_orders(id),
    application_no VARCHAR(80) NOT NULL UNIQUE,
    finance_company VARCHAR(160) NOT NULL,
    down_payment_amount NUMERIC(14, 2) NOT NULL,
    loan_amount NUMERIC(14, 2) NOT NULL,
    term_months INTEGER NOT NULL,
    interest_rate NUMERIC(8, 4) NOT NULL,
    status VARCHAR(20) NOT NULL,
    disbursed_amount NUMERIC(14, 2),
    disbursed_at TIMESTAMP WITH TIME ZONE,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR(50) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES sales_orders(id),
    branch_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    return_date DATE NOT NULL,
    return_amount NUMERIC(14, 2) NOT NULL,
    refund_amount NUMERIC(14, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id BIGINT NOT NULL REFERENCES sales_returns(id),
    order_item_id BIGINT NOT NULL REFERENCES sales_order_items(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    serial_id BIGINT REFERENCES product_serials(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    line_amount NUMERIC(14, 2) NOT NULL,
    serial_disposition VARCHAR(20) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sales_orders_status ON sales_orders(status);
CREATE INDEX IF NOT EXISTS idx_sales_orders_reservation_until ON sales_orders(reservation_until);
CREATE INDEX IF NOT EXISTS idx_product_serials_reservation ON product_serials(status, reservation_until);
CREATE INDEX IF NOT EXISTS idx_sales_payments_order ON sales_payments(order_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_quotations_status_valid_until ON quotations(status, valid_until);
CREATE INDEX IF NOT EXISTS idx_sales_returns_order ON sales_returns(order_id);
