-- Professional Warranty & Service schema reference.
-- Development uses Hibernate ddl-auto=update; this documents the production target.

ALTER TABLE warranties ADD COLUMN IF NOT EXISTS policy_id BIGINT;
ALTER TABLE warranties ADD COLUMN IF NOT EXISTS battery_end_date DATE;
ALTER TABLE warranties ADD COLUMN IF NOT EXISTS motor_end_date DATE;
ALTER TABLE warranties ADD COLUMN IF NOT EXISTS charger_end_date DATE;
ALTER TABLE warranties ADD COLUMN IF NOT EXISTS main_parts_warranty VARCHAR(1000);

ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS customer_id BIGINT;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(30);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS before_repair_images VARCHAR(1000);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS diagnosis_note VARCHAR(1000);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS predicted_cause VARCHAR(1000);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS warranty_repair BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS labor_cost NUMERIC(12, 2) DEFAULT 0 NOT NULL;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS parts_cost NUMERIC(12, 2) DEFAULT 0 NOT NULL;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS warranty_cost NUMERIC(12, 2) DEFAULT 0 NOT NULL;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS returned_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE service_ticket_items ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE service_ticket_items ADD COLUMN IF NOT EXISTS warehouse_id BIGINT;
ALTER TABLE service_ticket_items ADD COLUMN IF NOT EXISTS unit_cost NUMERIC(12, 2) DEFAULT 0 NOT NULL;

CREATE TABLE IF NOT EXISTS warranty_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name VARCHAR(160) NOT NULL,
    product_category VARCHAR(40) NOT NULL,
    warranty_months INTEGER NOT NULL,
    battery_warranty_months INTEGER NOT NULL,
    motor_warranty_months INTEGER NOT NULL,
    included_parts VARCHAR(1000),
    excluded_cases VARCHAR(1000),
    labor_fee_policy VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS repair_quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_no VARCHAR(60) NOT NULL UNIQUE,
    ticket_id BIGINT NOT NULL,
    parts_amount NUMERIC(12, 2) NOT NULL,
    labor_amount NUMERIC(12, 2) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    approved_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS service_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(60) NOT NULL UNIQUE,
    ticket_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS service_ticket_timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    event_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_service_ticket_status ON service_tickets(status);
CREATE INDEX IF NOT EXISTS idx_service_ticket_technician ON service_tickets(technician_username);
CREATE INDEX IF NOT EXISTS idx_repair_quotation_ticket ON repair_quotations(ticket_id, created_at);
CREATE INDEX IF NOT EXISTS idx_service_timeline_ticket ON service_ticket_timeline(ticket_id, event_time);
