-- CRM schema reference for ERP-grade customer management.
-- Development still uses Hibernate ddl-auto=update; this file documents the target surface.

ALTER TABLE customers ADD COLUMN IF NOT EXISTS assigned_to BIGINT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS birthday VARCHAR(40);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tier VARCHAR(30) DEFAULT 'NEW' NOT NULL;

CREATE TABLE IF NOT EXISTS crm_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_name VARCHAR(160) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    source VARCHAR(30) NOT NULL,
    interested_product VARCHAR(180),
    assigned_to BIGINT,
    status VARCHAR(30) NOT NULL,
    lost_reason VARCHAR(300),
    note VARCHAR(1000),
    converted_customer_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS crm_opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    lead_id BIGINT,
    expected_value NUMERIC(14, 2) NOT NULL,
    expected_close_date DATE,
    stage VARCHAR(30) NOT NULL,
    probability INTEGER NOT NULL,
    assigned_to BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS crm_care_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    lead_id BIGINT,
    title VARCHAR(180) NOT NULL,
    content VARCHAR(1000),
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    due_date DATE,
    assigned_to BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS crm_customer_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    content VARCHAR(1200) NOT NULL,
    created_by VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_crm_leads_status_source ON crm_leads(status, source);
CREATE INDEX IF NOT EXISTS idx_crm_opportunities_stage ON crm_opportunities(stage, expected_close_date);
CREATE INDEX IF NOT EXISTS idx_crm_tasks_status_due_date ON crm_care_tasks(status, due_date);
CREATE INDEX IF NOT EXISTS idx_crm_notes_customer ON crm_customer_notes(customer_id, created_at);
