CREATE TABLE chart_of_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code VARCHAR(30) NOT NULL UNIQUE,
    account_name VARCHAR(160) NOT NULL,
    account_type VARCHAR(30) NOT NULL,
    parent_account_id BIGINT REFERENCES chart_of_accounts(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    description VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date DATE NOT NULL,
    reference_type VARCHAR(40) NOT NULL,
    reference_id VARCHAR(80),
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    created_by VARCHAR(120) NOT NULL,
    posted_by VARCHAR(120),
    total_debit NUMERIC(18, 2) NOT NULL DEFAULT 0,
    total_credit NUMERIC(18, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    posted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE journal_entry_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES journal_entries(id),
    account_id BIGINT NOT NULL REFERENCES chart_of_accounts(id),
    debit_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    description VARCHAR(500)
);

ALTER TABLE receivables ADD COLUMN IF NOT EXISTS invoice_no VARCHAR(80);
ALTER TABLE receivables ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE receivables ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'UNPAID';

ALTER TABLE payables ADD COLUMN IF NOT EXISTS invoice_no VARCHAR(80);
ALTER TABLE payables ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE payables ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'UNPAID';

CREATE INDEX idx_chart_of_accounts_code ON chart_of_accounts(account_code);
CREATE INDEX idx_journal_entries_date_status ON journal_entries(entry_date, status);
CREATE INDEX idx_journal_entries_reference ON journal_entries(reference_type, reference_id);
CREATE INDEX idx_journal_entry_lines_account ON journal_entry_lines(account_id);
