-- V19: Warehouse Management Upgrade
-- Them loai kho moi, phieu nhap/xuat/kiem ke day du

-- ────────────────────────────────────────────
-- 1. Warehouse: them location fields
-- ────────────────────────────────────────────
ALTER TABLE warehouses
    ADD COLUMN IF NOT EXISTS location_aisle   VARCHAR(40)  NULL,
    ADD COLUMN IF NOT EXISTS location_shelf   VARCHAR(40)  NULL,
    ADD COLUMN IF NOT EXISTS location_bin     VARCHAR(40)  NULL,
    ADD COLUMN IF NOT EXISTS description      VARCHAR(500) NULL;

COMMENT ON COLUMN warehouses.location_aisle IS 'Day/lo trong kho';
COMMENT ON COLUMN warehouses.location_shelf IS 'Ke/tang';
COMMENT ON COLUMN warehouses.location_bin   IS 'O/vi tri cu the';

-- WarehouseType moi: DISPLAY, WARRANTY_STORE, DEFECTIVE_STORE, STAGING, SPARE_PARTS
-- (PostgreSQL VARCHAR enum khong can ALTER TYPE)

-- ────────────────────────────────────────────
-- 2. Purchase Receipts (Phieu nhap kho)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_receipts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no          VARCHAR(80)      NOT NULL UNIQUE,
    purchase_order_id   BIGINT           REFERENCES purchase_orders(id),
    supplier_id         BIGINT           REFERENCES suppliers(id),
    branch_id           BIGINT           NOT NULL REFERENCES branches(id),
    warehouse_id        BIGINT           REFERENCES warehouses(id),
    receipt_date        DATE             NOT NULL DEFAULT CURRENT_DATE,
    status              VARCHAR(30)      NOT NULL DEFAULT 'DRAFT',   -- DRAFT, CONFIRMED, CANCELLED
    total_amount        NUMERIC(14,2)    NOT NULL DEFAULT 0,
    note                VARCHAR(500),
    created_by          VARCHAR(120)     NOT NULL,
    confirmed_by        VARCHAR(120),
    confirmed_at        TIMESTAMP WITH TIME ZONE,
    accounting_recorded BOOLEAN          NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_receipt_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id     BIGINT           NOT NULL REFERENCES purchase_receipts(id) ON DELETE CASCADE,
    product_id     BIGINT           NOT NULL REFERENCES products(id),
    quantity       INTEGER          NOT NULL DEFAULT 1,
    unit_cost      NUMERIC(14,2)    NOT NULL DEFAULT 0,
    line_total     NUMERIC(14,2)    NOT NULL DEFAULT 0,
    -- Serial info cho xe dien (co the NULL cho phu tung)
    frame_number   VARCHAR(80),
    engine_number  VARCHAR(80),
    battery_serial VARCHAR(80),
    serial_number  VARCHAR(80),    -- Serial xe tao ra sau confirm
    note           VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_purchase_receipts_branch_status
    ON purchase_receipts(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_po
    ON purchase_receipts(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipt_items_receipt
    ON purchase_receipt_items(receipt_id);

-- ────────────────────────────────────────────
-- 3. Inventory Counts (Phieu kiem ke)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventory_counts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count_no     VARCHAR(80)  NOT NULL UNIQUE,
    branch_id    BIGINT       NOT NULL REFERENCES branches(id),
    warehouse_id BIGINT       REFERENCES warehouses(id),
    count_date   DATE         NOT NULL DEFAULT CURRENT_DATE,
    status       VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
        -- DRAFT, COUNTING, PENDING_APPROVAL, APPROVED, CANCELLED
    note         VARCHAR(500),
    created_by   VARCHAR(120) NOT NULL,
    approved_by  VARCHAR(120),
    approved_at  TIMESTAMP WITH TIME ZONE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_count_items (
    id                BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count_id          BIGINT           NOT NULL REFERENCES inventory_counts(id) ON DELETE CASCADE,
    product_id        BIGINT           NOT NULL REFERENCES products(id),
    system_quantity   INTEGER          NOT NULL DEFAULT 0,
    counted_quantity  INTEGER,        -- NULL = chua kiem
    variance_qty      INTEGER          GENERATED ALWAYS AS (
                            CASE WHEN counted_quantity IS NOT NULL
                                 THEN counted_quantity - system_quantity
                                 ELSE 0 END
                          ) STORED,
    variance_reason   VARCHAR(500),
    adjustment_applied BOOLEAN         NOT NULL DEFAULT FALSE,
    note              VARCHAR(500)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_inventory_count_items_count_product
    ON inventory_count_items(count_id, product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_counts_branch_status
    ON inventory_counts(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_inventory_count_items_count
    ON inventory_count_items(count_id);

-- ────────────────────────────────────────────
-- 4. Goods Issues (Phieu xuat kho)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS goods_issues (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_no        VARCHAR(80)  NOT NULL UNIQUE,
    branch_id       BIGINT       NOT NULL REFERENCES branches(id),
    warehouse_id    BIGINT       REFERENCES warehouses(id),
    issue_date      DATE         NOT NULL DEFAULT CURRENT_DATE,
    issue_type      VARCHAR(30)  NOT NULL,
        -- SALE, WARRANTY, SERVICE, TRANSFER, WRITE_OFF, OTHER
    status          VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
        -- DRAFT, ISSUED, CANCELLED
    reference_type  VARCHAR(80),
    reference_no    VARCHAR(80),
    note            VARCHAR(500),
    created_by      VARCHAR(120) NOT NULL,
    issued_by       VARCHAR(120),
    issued_at       TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS goods_issue_items (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id    BIGINT          NOT NULL REFERENCES goods_issues(id) ON DELETE CASCADE,
    product_id  BIGINT          NOT NULL REFERENCES products(id),
    quantity    INTEGER         NOT NULL DEFAULT 1,
    unit_cost   NUMERIC(14,2)   NOT NULL DEFAULT 0,
    serial_id   BIGINT          REFERENCES product_serials(id),
    note        VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_goods_issues_branch_status
    ON goods_issues(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_goods_issue_items_issue
    ON goods_issue_items(issue_id);

-- ────────────────────────────────────────────
-- 5. Stock Transfer Items (multi-item per transfer)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventory_transfer_items (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT          NOT NULL REFERENCES inventory_transfers(id) ON DELETE CASCADE,
    product_id  BIGINT          NOT NULL REFERENCES products(id),
    quantity    INTEGER         NOT NULL DEFAULT 1,
    unit_cost   NUMERIC(14,2)   NOT NULL DEFAULT 0,
    serial_id   BIGINT          REFERENCES product_serials(id),
    note        VARCHAR(500)
);

-- Them fields con thieu cho inventory_transfers
ALTER TABLE inventory_transfers
    ADD COLUMN IF NOT EXISTS cancelled_at      TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS cancelled_by      VARCHAR(120),
    ADD COLUMN IF NOT EXISTS rejection_reason  VARCHAR(500);

CREATE INDEX IF NOT EXISTS idx_inventory_transfer_items_transfer
    ON inventory_transfer_items(transfer_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_branch_status
    ON inventory_transfers(from_branch_id, status);

COMMENT ON TABLE purchase_receipts IS 'Phieu nhap kho tu don mua hang hoac nhap tu nha cung cap';
COMMENT ON TABLE inventory_counts  IS 'Phieu kiem ke ton kho theo kho/chi nhanh';
COMMENT ON TABLE goods_issues      IS 'Phieu xuat kho (ban hang, bao hanh, chuyen kho, huy)';

-- ────────────────────────────────────────────
-- 6. Seed permissions moi cho module kho
-- ────────────────────────────────────────────
INSERT INTO permissions (code, module, action) VALUES
('INVENTORY_ADJUST','INVENTORY','ADJUST'),
('INVENTORY_ADJUST_APPROVE','INVENTORY','ADJUST_APPROVE'),
('INVENTORY_WRITE_OFF','INVENTORY','WRITE_OFF')
ON CONFLICT (code) DO NOTHING;

-- Grant cho ADMIN (tu dong qua ALL GRANT trong V2)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'ADMIN'
  AND p.code IN ('INVENTORY_ADJUST','INVENTORY_ADJUST_APPROVE','INVENTORY_WRITE_OFF')
ON CONFLICT DO NOTHING;

-- WAREHOUSE_STAFF: duoc nhap, xuat, dieu chinh (khong duoc duyet)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'WAREHOUSE_STAFF'
  AND p.code IN ('INVENTORY_VIEW','INVENTORY_IMPORT','INVENTORY_EXPORT','INVENTORY_ADJUST')
ON CONFLICT DO NOTHING;

-- BRANCH_MANAGER: duoc duyet kiem ke va write-off
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'BRANCH_MANAGER'
  AND p.code IN ('INVENTORY_VIEW','INVENTORY_IMPORT','INVENTORY_EXPORT',
                 'INVENTORY_ADJUST','INVENTORY_ADJUST_APPROVE','INVENTORY_WRITE_OFF',
                 'INVENTORY_TRANSFER','INVENTORY_APPROVE')
ON CONFLICT DO NOTHING;

