CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    module VARCHAR(60) NOT NULL,
    action VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    address VARCHAR(255),
    phone VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(160) NOT NULL UNIQUE,
    phone VARCHAR(30),
    full_name VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    branch_id BIGINT REFERENCES branches(id),
    role_id BIGINT REFERENCES roles(id),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS user_branch_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    access_level VARCHAR(30) NOT NULL,
    UNIQUE (user_id, branch_id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(80) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(80) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(80) NOT NULL UNIQUE,
    product_name VARCHAR(180) NOT NULL,
    category VARCHAR(40) NOT NULL,
    brand VARCHAR(80),
    model VARCHAR(80),
    color VARCHAR(60),
    battery_capacity VARCHAR(80),
    motor_power VARCHAR(80),
    import_price NUMERIC(14,2) NOT NULL DEFAULT 0,
    sale_price NUMERIC(14,2) NOT NULL DEFAULT 0,
    warranty_months INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    image_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code VARCHAR(80) NOT NULL UNIQUE,
    warehouse_name VARCHAR(160) NOT NULL,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    type VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(30) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(120),
    address VARCHAR(255),
    source VARCHAR(50),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    assigned_to BIGINT,
    birthday VARCHAR(40),
    tier VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code VARCHAR(80) NOT NULL UNIQUE,
    supplier_name VARCHAR(180) NOT NULL,
    phone VARCHAR(30),
    email VARCHAR(120),
    address VARCHAR(255),
    tax_code VARCHAR(80),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_serials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    serial_number VARCHAR(80) NOT NULL UNIQUE,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    warehouse_id BIGINT REFERENCES warehouses(id),
    frame_number VARCHAR(80),
    engine_number VARCHAR(80),
    battery_serial VARCHAR(80),
    motor_serial VARCHAR(80),
    import_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(30) NOT NULL,
    reserved_order_no VARCHAR(80),
    reservation_until TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS inventory_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    warehouse_id BIGINT REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity_on_hand INTEGER NOT NULL DEFAULT 0,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    min_quantity INTEGER NOT NULL DEFAULT 0,
    max_quantity INTEGER NOT NULL DEFAULT 0,
    average_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (branch_id, product_id)
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(30) NOT NULL,
    transaction_no VARCHAR(80) NOT NULL UNIQUE,
    transaction_date DATE NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(id),
    from_branch_id BIGINT,
    to_branch_id BIGINT,
    from_warehouse_id BIGINT,
    to_warehouse_id BIGINT,
    quantity INTEGER NOT NULL,
    unit_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    reference_type VARCHAR(50),
    reference_no VARCHAR(80),
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_no VARCHAR(80) NOT NULL UNIQUE,
    supplier_id BIGINT REFERENCES suppliers(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    order_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_cost NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_no VARCHAR(50) NOT NULL UNIQUE,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    employee_id BIGINT NOT NULL REFERENCES app_users(id),
    quotation_date DATE NOT NULL,
    valid_until DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    subtotal NUMERIC(14,2) NOT NULL,
    discount_amount NUMERIC(14,2) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL,
    voucher_code VARCHAR(50),
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id BIGINT NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    serial_id BIGINT REFERENCES product_serials(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    employee_id BIGINT NOT NULL REFERENCES app_users(id),
    quotation_id BIGINT REFERENCES quotations(id),
    order_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    voucher_code VARCHAR(50),
    note VARCHAR(500),
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(20) NOT NULL,
    reservation_until TIMESTAMP WITH TIME ZONE,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    returned_at TIMESTAMP WITH TIME ZONE,
    accounting_recorded BOOLEAN NOT NULL DEFAULT FALSE,
    stock_issued BOOLEAN NOT NULL DEFAULT FALSE,
    warranty_created BOOLEAN NOT NULL DEFAULT FALSE,
    voucher_consumed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    serial_id BIGINT REFERENCES product_serials(id),
    warehouse_id BIGINT REFERENCES warehouses(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL,
    returned_quantity INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(80) NOT NULL UNIQUE,
    order_id BIGINT REFERENCES sales_orders(id),
    invoice_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL,
    vat_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    template_code VARCHAR(80),
    template_snapshot VARCHAR(2000),
    electronic_invoice_provider VARCHAR(80),
    electronic_invoice_status VARCHAR(40),
    electronic_invoice_ref VARCHAR(120),
    issued_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_orders(id),
    payment_method VARCHAR(30) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    payment_date DATE NOT NULL,
    bank_account_id BIGINT,
    reference_no VARCHAR(80),
    note VARCHAR(500),
    installment_disbursement BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS installment_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_orders(id),
    application_no VARCHAR(80) NOT NULL UNIQUE,
    finance_company VARCHAR(160) NOT NULL,
    down_payment_amount NUMERIC(14,2) NOT NULL,
    loan_amount NUMERIC(14,2) NOT NULL,
    term_months INTEGER NOT NULL,
    interest_rate NUMERIC(8,4) NOT NULL,
    status VARCHAR(20) NOT NULL,
    disbursed_amount NUMERIC(14,2),
    disbursed_at TIMESTAMP WITH TIME ZONE,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR(50) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES sales_orders(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    return_date DATE NOT NULL,
    return_amount NUMERIC(14,2) NOT NULL,
    refund_amount NUMERIC(14,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id BIGINT NOT NULL REFERENCES sales_returns(id) ON DELETE CASCADE,
    order_item_id BIGINT NOT NULL REFERENCES sales_order_items(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    serial_id BIGINT REFERENCES product_serials(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_amount NUMERIC(14,2) NOT NULL,
    serial_disposition VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(120) NOT NULL,
    action VARCHAR(50) NOT NULL,
    module VARCHAR(50) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(80),
    user_agent VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(120) NOT NULL UNIQUE,
    setting_value TEXT,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS inventory_average_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL DEFAULT 0,
    average_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (branch_id, warehouse_id, product_id)
);

CREATE TABLE IF NOT EXISTS inventory_cost_layers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    layer_date DATE NOT NULL,
    quantity INTEGER NOT NULL,
    remaining_quantity INTEGER NOT NULL,
    unit_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    source_type VARCHAR(50),
    source_no VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_no VARCHAR(80) NOT NULL UNIQUE,
    branch_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    serial_id BIGINT REFERENCES product_serials(id),
    quantity INTEGER NOT NULL,
    sales_order_no VARCHAR(80),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no VARCHAR(80) NOT NULL UNIQUE,
    transfer_date DATE NOT NULL,
    from_branch_id BIGINT NOT NULL,
    to_branch_id BIGINT NOT NULL,
    from_warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    to_warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    transfer_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP WITH TIME ZONE,
    shipped_at TIMESTAMP WITH TIME ZONE,
    received_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS inventory_stocktakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_no VARCHAR(80) NOT NULL UNIQUE,
    stocktake_date DATE NOT NULL,
    branch_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    system_quantity INTEGER NOT NULL,
    counted_quantity INTEGER NOT NULL,
    variance_quantity INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adjusted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS warranty_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name VARCHAR(160) NOT NULL,
    product_category VARCHAR(50) NOT NULL,
    warranty_months INTEGER NOT NULL,
    battery_warranty_months INTEGER,
    motor_warranty_months INTEGER,
    included_parts TEXT,
    excluded_cases TEXT,
    labor_fee_policy TEXT
);

CREATE TABLE IF NOT EXISTS warranties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number VARCHAR(80) NOT NULL UNIQUE,
    vehicle_id BIGINT,
    customer_id BIGINT,
    customer_name VARCHAR(160) NOT NULL,
    invoice_no VARCHAR(80),
    purchase_date DATE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    battery_end_date DATE,
    motor_end_date DATE,
    charger_end_date DATE,
    status VARCHAR(30) NOT NULL,
    covered_parts TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    serial_number VARCHAR(80),
    customer_name VARCHAR(160) NOT NULL,
    phone VARCHAR(30),
    issue_description TEXT NOT NULL,
    technician_username VARCHAR(80),
    status VARCHAR(40) NOT NULL,
    warranty_repair BOOLEAN NOT NULL DEFAULT FALSE,
    total_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    before_repair_images TEXT,
    after_repair_images TEXT,
    diagnosis TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS service_ticket_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES service_tickets(id) ON DELETE CASCADE,
    item_type VARCHAR(40) NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL,
    warranty_covered BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS service_ticket_timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES service_tickets(id) ON DELETE CASCADE,
    status VARCHAR(40) NOT NULL,
    note TEXT,
    username VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS repair_quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES service_tickets(id),
    quotation_no VARCHAR(80) NOT NULL UNIQUE,
    total_amount NUMERIC(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS service_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES service_tickets(id),
    invoice_no VARCHAR(80) NOT NULL UNIQUE,
    total_amount NUMERIC(14,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR(120) NOT NULL,
    account_number VARCHAR(80) NOT NULL UNIQUE,
    account_holder VARCHAR(160) NOT NULL,
    current_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS chart_of_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code VARCHAR(40) NOT NULL UNIQUE,
    account_name VARCHAR(160) NOT NULL,
    account_type VARCHAR(40) NOT NULL,
    parent_code VARCHAR(40),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_no VARCHAR(80) NOT NULL UNIQUE,
    entry_date DATE NOT NULL,
    source_type VARCHAR(50),
    source_no VARCHAR(80),
    status VARCHAR(30) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    posted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    account_code VARCHAR(40) NOT NULL,
    description VARCHAR(500),
    debit_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(14,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS receivables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    customer_name VARCHAR(160) NOT NULL,
    source_no VARCHAR(80),
    source_type VARCHAR(50),
    transaction_date DATE NOT NULL,
    due_date DATE,
    debit_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS payables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT,
    supplier_name VARCHAR(160) NOT NULL,
    source_no VARCHAR(80),
    source_type VARCHAR(50),
    transaction_date DATE NOT NULL,
    due_date DATE,
    debit_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS accounting_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_no VARCHAR(80) NOT NULL UNIQUE,
    transaction_date DATE NOT NULL,
    type VARCHAR(50) NOT NULL,
    source_type VARCHAR(50),
    source_no VARCHAR(80),
    party_id BIGINT,
    party_name VARCHAR(160),
    amount NUMERIC(14,2) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cash_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date DATE NOT NULL,
    type VARCHAR(40) NOT NULL,
    source_type VARCHAR(50),
    source_no VARCHAR(80),
    amount_in NUMERIC(14,2) NOT NULL DEFAULT 0,
    amount_out NUMERIC(14,2) NOT NULL DEFAULT 0,
    balance_after NUMERIC(14,2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(40),
    bank_account_id BIGINT,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS crm_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(120),
    source VARCHAR(50),
    status VARCHAR(40) NOT NULL,
    branch_id BIGINT,
    assigned_to BIGINT,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT,
    customer_id BIGINT,
    title VARCHAR(160) NOT NULL,
    stage VARCHAR(40) NOT NULL,
    expected_value NUMERIC(14,2) NOT NULL DEFAULT 0,
    branch_id BIGINT,
    assigned_to BIGINT,
    expected_close_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_customer_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    username VARCHAR(80),
    note TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_care_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    title VARCHAR(160) NOT NULL,
    type VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    assigned_to BIGINT,
    due_date DATE,
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS marketing_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_name VARCHAR(160) NOT NULL,
    channel VARCHAR(80),
    start_date DATE,
    end_date DATE,
    budget NUMERIC(14,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    note VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    discount_type VARCHAR(30) NOT NULL,
    discount_value NUMERIC(14,2) NOT NULL,
    minimum_order_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    usage_limit INTEGER NOT NULL DEFAULT 0,
    used_count INTEGER NOT NULL DEFAULT 0,
    start_date DATE,
    end_date DATE,
    applicable_product_ids VARCHAR(500),
    applicable_branch_ids VARCHAR(500),
    status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(80) NOT NULL,
    severity VARCHAR(30) NOT NULL,
    module VARCHAR(80) NOT NULL,
    entity_id BIGINT,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (type, module, entity_id)
);

CREATE TABLE IF NOT EXISTS notification_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    username VARCHAR(80) NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (notification_id, username)
);

CREATE TABLE IF NOT EXISTS reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    username VARCHAR(80),
    type VARCHAR(60) NOT NULL,
    status VARCHAR(40) NOT NULL,
    title VARCHAR(160) NOT NULL,
    note VARCHAR(500),
    remind_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS system_error_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity VARCHAR(40) NOT NULL,
    source VARCHAR(120),
    message TEXT NOT NULL,
    stack_trace TEXT,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
