ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS branch_id BIGINT;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS customer_reported_issue VARCHAR(1000);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS received_date DATE;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS expected_return_date DATE;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS actual_return_date DATE;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS fault_images VARCHAR(1000);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS after_repair_images VARCHAR(1000);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS document_files VARCHAR(1000);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS service_type VARCHAR(30) DEFAULT 'WARRANTY' NOT NULL;
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS component_type VARCHAR(30);
ALTER TABLE service_tickets ADD COLUMN IF NOT EXISTS customer_pay_amount NUMERIC(12, 2) DEFAULT 0 NOT NULL;

ALTER TABLE service_ticket_items ADD COLUMN IF NOT EXISTS warranty_covered BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE service_ticket_items ADD COLUMN IF NOT EXISTS component_type VARCHAR(30);

CREATE TABLE IF NOT EXISTS warranty_policy_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    component_type VARCHAR(30) NOT NULL,
    warranty_months INTEGER NOT NULL,
    warranty_km INTEGER,
    conditions VARCHAR(1000),
    exclusions VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS warranty_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warranty_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    serial_id BIGINT NOT NULL,
    customer_id BIGINT,
    component_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    warranty_km INTEGER,
    conditions VARCHAR(1000),
    exclusions VARCHAR(1000),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_warranty_policy_details_product_component ON warranty_policy_details(product_id, component_type);
CREATE INDEX IF NOT EXISTS idx_warranty_components_serial_component ON warranty_components(serial_id, component_type, end_date);
CREATE INDEX IF NOT EXISTS idx_service_tickets_component ON service_tickets(component_type);
CREATE INDEX IF NOT EXISTS idx_service_tickets_service_type ON service_tickets(service_type);
