ALTER TABLE employee_kpis ADD COLUMN IF NOT EXISTS profit NUMERIC(14, 2) DEFAULT 0;

CREATE TABLE IF NOT EXISTS payroll_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payrolls(id),
    item_type VARCHAR(40) NOT NULL,
    description VARCHAR(160) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_payroll_items_payroll ON payroll_items(payroll_id);

INSERT INTO permissions (code, module, action)
VALUES ('HR_MANAGE', 'HR', 'MANAGE')
ON CONFLICT (code) DO NOTHING;
