CREATE TABLE IF NOT EXISTS price_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code VARCHAR(60) NOT NULL UNIQUE,
    policy_name VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    scope_type VARCHAR(30) NOT NULL,
    price_change_type VARCHAR(30) NOT NULL,
    value NUMERIC(14, 2) NOT NULL DEFAULT 0,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    priority INTEGER NOT NULL DEFAULT 0,
    created_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    approved_by VARCHAR(120),
    approved_at TIMESTAMP WITH TIME ZONE,
    cancelled_by VARCHAR(120),
    cancelled_at TIMESTAMP WITH TIME ZONE,
    note VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS price_policy_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_policy_id BIGINT NOT NULL REFERENCES price_policies(id),
    branch_id BIGINT,
    product_id BIGINT,
    category_id BIGINT,
    brand_id BIGINT,
    category_code VARCHAR(60),
    brand VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS product_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    old_base_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
    new_base_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
    old_selling_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
    new_selling_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
    reason VARCHAR(500),
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT,
    changed_by VARCHAR(120) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    branch_id BIGINT,
    note VARCHAR(1000)
);

ALTER TABLE sales_order_items ADD COLUMN IF NOT EXISTS list_price NUMERIC(14, 2);
ALTER TABLE sales_order_items ADD COLUMN IF NOT EXISTS price_policy_id BIGINT;
ALTER TABLE sales_order_items ADD COLUMN IF NOT EXISTS price_policy_code VARCHAR(60);
ALTER TABLE sales_order_items ADD COLUMN IF NOT EXISTS price_policy_name VARCHAR(160);
ALTER TABLE sales_order_items ADD COLUMN IF NOT EXISTS policy_discount_amount NUMERIC(14, 2) DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_price_policies_effective ON price_policies(status, start_date, end_date, priority, created_at);
CREATE INDEX IF NOT EXISTS idx_price_policy_targets_policy ON price_policy_targets(price_policy_id);
CREATE INDEX IF NOT EXISTS idx_product_price_history_product ON product_price_history(product_id, changed_at);
CREATE INDEX IF NOT EXISTS idx_sales_order_items_policy ON sales_order_items(price_policy_id);

INSERT INTO permissions (code, module, action)
VALUES
    ('VIEW_PRICE_POLICY', 'PRICING', 'VIEW'),
    ('CREATE_PRICE_POLICY', 'PRICING', 'CREATE'),
    ('EDIT_PRICE_POLICY', 'PRICING', 'EDIT'),
    ('APPROVE_PRICE_POLICY', 'PRICING', 'APPROVE'),
    ('CANCEL_PRICE_POLICY', 'PRICING', 'CANCEL'),
    ('VIEW_PRICE_HISTORY', 'PRICING', 'VIEW'),
    ('EDIT_BASE_PRICE', 'PRICING', 'EDIT'),
    ('VIEW_COST_PRICE', 'PRICING', 'VIEW'),
    ('VIEW_PROFIT', 'PRICING', 'VIEW'),
    ('APPROVE_SELL_BELOW_COST', 'PRICING', 'APPROVE')
ON CONFLICT (code) DO NOTHING;
