INSERT INTO permissions (code, module, action) VALUES
('DASHBOARD_VIEW','DASHBOARD','VIEW'),
('BRANCH_VIEW','BRANCH','VIEW'), ('BRANCH_CREATE','BRANCH','CREATE'), ('BRANCH_UPDATE','BRANCH','UPDATE'), ('BRANCH_DELETE','BRANCH','DELETE'),
('PRODUCT_VIEW','PRODUCT','VIEW'), ('PRODUCT_CREATE','PRODUCT','CREATE'), ('PRODUCT_UPDATE','PRODUCT','UPDATE'), ('PRODUCT_DELETE','PRODUCT','DELETE'), ('PRODUCT_EXPORT','PRODUCT','EXPORT'),
('INVENTORY_VIEW','INVENTORY','VIEW'), ('INVENTORY_IMPORT','INVENTORY','IMPORT'), ('INVENTORY_EXPORT','INVENTORY','EXPORT'), ('INVENTORY_TRANSFER','INVENTORY','TRANSFER'), ('INVENTORY_APPROVE','INVENTORY','APPROVE'), ('INVENTORY_STOCKTAKE','INVENTORY','STOCKTAKE'),
('SALES_VIEW','SALES','VIEW'), ('SALES_CREATE','SALES','CREATE'), ('SALES_UPDATE','SALES','UPDATE'), ('SALES_CANCEL','SALES','CANCEL'), ('SALES_RETURN','SALES','RETURN'), ('SALES_DISCOUNT_APPROVE','SALES','APPROVE'),
('INVOICE_ISSUE','INVOICE','ISSUE'), ('INVOICE_EXPORT','INVOICE','EXPORT'),
('CUSTOMER_VIEW','CUSTOMER','VIEW'), ('CUSTOMER_CREATE','CUSTOMER','CREATE'), ('CUSTOMER_UPDATE','CUSTOMER','UPDATE'),
('SUPPLIER_VIEW','SUPPLIER','VIEW'), ('SUPPLIER_CREATE','SUPPLIER','CREATE'), ('SUPPLIER_UPDATE','SUPPLIER','UPDATE'), ('PURCHASE_CREATE','PURCHASE','CREATE'),
('WARRANTY_VIEW','WARRANTY','VIEW'), ('WARRANTY_MANAGE','WARRANTY','MANAGE'),
('ACCOUNTING_VIEW','ACCOUNTING','VIEW'), ('ACCOUNTING_CREATE','ACCOUNTING','CREATE'), ('ACCOUNTING_POST','ACCOUNTING','POST'), ('ACCOUNTING_CANCEL','ACCOUNTING','CANCEL'), ('ACCOUNTING_REPORT','ACCOUNTING','REPORT'),
('RECEIPT_CREATE','ACCOUNTING','RECEIPT_CREATE'), ('PAYMENT_CREATE','ACCOUNTING','PAYMENT_CREATE'),
('REPORT_VIEW','REPORT','VIEW'), ('REPORT_EXPORT','REPORT','EXPORT'),
('MARKETING_VIEW','MARKETING','VIEW'), ('MARKETING_CREATE','MARKETING','CREATE'), ('MARKETING_UPDATE','MARKETING','UPDATE'),
('SETTING_VIEW','SETTING','VIEW'), ('SETTING_MANAGE','SETTING','MANAGE'),
('USER_VIEW','USER','VIEW'), ('USER_CREATE','USER','CREATE'), ('USER_UPDATE','USER','UPDATE'),
('ROLE_VIEW','ROLE','VIEW'), ('ROLE_UPDATE','ROLE','UPDATE'),
('AUDIT_VIEW','AUDIT','VIEW')
ON CONFLICT (code) DO UPDATE SET module = EXCLUDED.module, action = EXCLUDED.action;

INSERT INTO roles (code, name) VALUES
('ADMIN','Quan tri he thong'),
('BRANCH_MANAGER','Quan ly chi nhanh'),
('SALES_STAFF','Nhan vien ban hang'),
('WAREHOUSE_STAFF','Nhan vien kho'),
('ACCOUNTANT','Ke toan'),
('TECHNICIAN','Ky thuat vien'),
('MARKETING_STAFF','Marketing'),
('AUDITOR','Kiem toan noi bo')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.code = 'ADMIN'
ON CONFLICT DO NOTHING;
