-- V41: Accounting payables table required by AccountingPayable entity

CREATE TABLE IF NOT EXISTS accounting_payables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    supplier_name VARCHAR(120) NOT NULL,
    type VARCHAR(30) NOT NULL,
    transaction_date DATE NOT NULL,
    debit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    source_type VARCHAR(40) NOT NULL,
    source_no VARCHAR(80) NOT NULL,
    invoice_no VARCHAR(80),
    due_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    description VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_accounting_payables_supplier ON accounting_payables(supplier_id);
CREATE INDEX IF NOT EXISTS idx_accounting_payables_status_due ON accounting_payables(status, due_date);
CREATE INDEX IF NOT EXISTS idx_accounting_payables_source ON accounting_payables(source_type, source_no);
