-- PR4: supplier invoice three-way matching against PO and confirmed goods receipts.
ALTER TABLE supplier_invoices
    ADD COLUMN IF NOT EXISTS purchase_order_id BIGINT REFERENCES purchase_orders(id),
    ADD COLUMN IF NOT EXISTS match_details VARCHAR(2000),
    ADD COLUMN IF NOT EXISTS resolved_by VARCHAR(120),
    ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS resolve_reason VARCHAR(1000);

UPDATE supplier_invoices
SET purchase_order_id = pr.purchase_order_id
FROM purchase_receipts pr
WHERE supplier_invoices.receipt_id = pr.id
  AND supplier_invoices.purchase_order_id IS NULL;

UPDATE supplier_invoices
SET status = CASE
    WHEN status = 'VERIFIED' THEN 'MATCHED'
    WHEN status = 'RECEIVED' THEN 'PENDING_MATCH'
    ELSE status
END
WHERE status IN ('VERIFIED', 'RECEIVED');

ALTER TABLE supplier_invoices
    DROP CONSTRAINT IF EXISTS chk_supplier_invoice_status;

ALTER TABLE supplier_invoices
    ADD CONSTRAINT chk_supplier_invoice_status
    CHECK (status IN ('PENDING_MATCH', 'MATCHED', 'HOLD_FOR_REVIEW', 'RESOLVED'));

CREATE INDEX IF NOT EXISTS idx_supplier_invoices_po_status
    ON supplier_invoices(purchase_order_id, status);

CREATE TABLE IF NOT EXISTS supplier_invoice_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_invoice_id BIGINT NOT NULL REFERENCES supplier_invoices(id) ON DELETE CASCADE,
    product_id          BIGINT NOT NULL REFERENCES products(id),
    quantity            INTEGER NOT NULL,
    unit_price          NUMERIC(14,2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_supplier_invoice_items_invoice
    ON supplier_invoice_items(supplier_invoice_id);

CREATE INDEX IF NOT EXISTS idx_supplier_invoice_items_product
    ON supplier_invoice_items(product_id);
