-- PR5: ledger-style purchase payments for supplier invoices.
ALTER TABLE supplier_invoices
    ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) NOT NULL DEFAULT 'UNPAID';

ALTER TABLE supplier_invoices
    DROP CONSTRAINT IF EXISTS chk_supplier_invoice_payment_status;

ALTER TABLE supplier_invoices
    ADD CONSTRAINT chk_supplier_invoice_payment_status
    CHECK (payment_status IN ('UNPAID','PARTIALLY_PAID','PAID'));

CREATE TABLE IF NOT EXISTS purchase_payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_invoice_id BIGINT NOT NULL REFERENCES supplier_invoices(id),
    amount              NUMERIC(14,2) NOT NULL,
    payment_date        DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_method      VARCHAR(30) NOT NULL,
    reference_no        VARCHAR(80),
    note                VARCHAR(500),
    created_by          VARCHAR(120) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_purchase_payment_method CHECK (payment_method IN ('CASH','BANK_TRANSFER')),
    CONSTRAINT chk_purchase_payment_amount CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_purchase_payments_invoice_date
    ON purchase_payments(supplier_invoice_id, payment_date DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_supplier_invoices_status_payment
    ON supplier_invoices(status, payment_status);
