-- PR7: Purchase return workflow, supplier return credit, and supplier receivable tracking.
ALTER TABLE purchase_returns
    ADD COLUMN IF NOT EXISTS purchase_receipt_id BIGINT REFERENCES purchase_receipts(id),
    ADD COLUMN IF NOT EXISTS reason_code VARCHAR(30),
    ADD COLUMN IF NOT EXISTS reason_note VARCHAR(500),
    ADD COLUMN IF NOT EXISTS supplier_invoice_id BIGINT REFERENCES supplier_invoices(id),
    ADD COLUMN IF NOT EXISTS supplier_receivable_id BIGINT,
    ADD COLUMN IF NOT EXISTS shipped_back_by VARCHAR(120),
    ADD COLUMN IF NOT EXISTS shipped_back_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS credited_by VARCHAR(120),
    ADD COLUMN IF NOT EXISTS credited_at TIMESTAMPTZ;

ALTER TABLE purchase_returns
    DROP CONSTRAINT IF EXISTS chk_purchase_return_status;

UPDATE purchase_returns
SET reason_code = COALESCE(reason_code, 'OTHER'),
    reason_note = COALESCE(reason_note, reason),
    status = CASE
        WHEN status = 'DRAFT' THEN 'REQUESTED'
        WHEN status = 'COMPLETED' THEN 'CREDITED'
        WHEN status = 'CANCELLED' THEN 'REJECTED'
        ELSE status
    END;

ALTER TABLE purchase_returns
    ALTER COLUMN reason_code SET NOT NULL;

ALTER TABLE purchase_returns
    ADD CONSTRAINT chk_purchase_return_status
    CHECK (status IN ('REQUESTED','APPROVED','SHIPPED_BACK','CREDITED','REFUND_RECEIVED','REJECTED'));

ALTER TABLE purchase_returns
    DROP CONSTRAINT IF EXISTS chk_purchase_return_reason_code;

ALTER TABLE purchase_returns
    ADD CONSTRAINT chk_purchase_return_reason_code
    CHECK (reason_code IN ('DEFECTIVE','WRONG_ITEM','QUALITY_ISSUE','OTHER'));

ALTER TABLE purchase_return_items
    ADD COLUMN IF NOT EXISTS purchase_receipt_item_id BIGINT REFERENCES purchase_receipt_items(id),
    ADD COLUMN IF NOT EXISTS batch_id BIGINT;

ALTER TABLE purchase_payments
    ADD COLUMN IF NOT EXISTS entry_type VARCHAR(30) NOT NULL DEFAULT 'PAYMENT';

ALTER TABLE purchase_payments
    DROP CONSTRAINT IF EXISTS chk_purchase_payment_entry_type;

ALTER TABLE purchase_payments
    ADD CONSTRAINT chk_purchase_payment_entry_type
    CHECK (entry_type IN ('PAYMENT','RETURN_CREDIT'));

CREATE TABLE IF NOT EXISTS supplier_receivables (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         BIGINT NOT NULL REFERENCES suppliers(id),
    purchase_return_id  BIGINT NOT NULL REFERENCES purchase_returns(id),
    supplier_invoice_id BIGINT REFERENCES supplier_invoices(id),
    branch_id           BIGINT NOT NULL REFERENCES branches(id),
    amount              NUMERIC(14,2) NOT NULL,
    receivable_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    status              VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    note                VARCHAR(500),
    created_by          VARCHAR(120) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_supplier_receivable_status CHECK (status IN ('OPEN','SETTLED','CANCELLED')),
    CONSTRAINT chk_supplier_receivable_amount CHECK (amount > 0)
);

ALTER TABLE purchase_returns
    DROP CONSTRAINT IF EXISTS fk_purchase_returns_supplier_receivable;

ALTER TABLE purchase_returns
    ADD CONSTRAINT fk_purchase_returns_supplier_receivable
    FOREIGN KEY (supplier_receivable_id) REFERENCES supplier_receivables(id);

CREATE INDEX IF NOT EXISTS idx_purchase_returns_receipt
    ON purchase_returns(purchase_receipt_id);

CREATE INDEX IF NOT EXISTS idx_purchase_return_items_receipt_item
    ON purchase_return_items(purchase_receipt_item_id);

CREATE INDEX IF NOT EXISTS idx_purchase_payments_invoice_entry_type
    ON purchase_payments(supplier_invoice_id, entry_type);

CREATE INDEX IF NOT EXISTS idx_supplier_receivables_supplier_status
    ON supplier_receivables(supplier_id, status);
