CREATE TABLE IF NOT EXISTS employee_warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id),
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    access_level VARCHAR(20) NOT NULL DEFAULT 'VIEW',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employee_warehouse UNIQUE (employee_id, warehouse_id),
    CONSTRAINT ck_employee_warehouse_access_level CHECK (access_level IN ('VIEW', 'OPERATE', 'MANAGE'))
);

CREATE INDEX IF NOT EXISTS idx_employee_warehouses_employee
    ON employee_warehouses(employee_id, active);

CREATE INDEX IF NOT EXISTS idx_employee_warehouses_warehouse
    ON employee_warehouses(warehouse_id);

-- Preserve current access before fail-closed enforcement: explicit branch assignments.
INSERT INTO employee_warehouses (employee_id, warehouse_id, access_level, active)
SELECT DISTINCT e.id, w.id, 'OPERATE', TRUE
FROM employees e
JOIN user_branch_access uba ON uba.user_id = e.user_id
JOIN warehouses w ON w.branch_id = uba.branch_id
WHERE e.user_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM employee_warehouses existing
      WHERE existing.employee_id = e.id AND existing.warehouse_id = w.id
  );

-- Preserve legacy users that still use app_users.branch_id instead of user_branch_access.
INSERT INTO employee_warehouses (employee_id, warehouse_id, access_level, active)
SELECT DISTINCT e.id, w.id, 'OPERATE', TRUE
FROM employees e
JOIN app_users u ON u.id = e.user_id
JOIN warehouses w ON w.branch_id = u.branch_id
WHERE e.user_id IS NOT NULL AND u.branch_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM employee_warehouses existing
      WHERE existing.employee_id = e.id AND existing.warehouse_id = w.id
  );
